/*
Copyright 2026 The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConnectedCluster records a single kbind bundle that was generated by the portal.
// It lives on the provider cluster and tracks both the API selection the user
// made and whether a consumer is actively heartbeating against this bundle.
// Cluster-scoped. Multiple ConnectedCluster objects may exist for the same consumer
// workspace (one per bundle generated).
//
// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Cluster,categories=kbind-provider
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Connected",type=string,JSONPath=`.status.conditions[?(@.type=="Connected")].status`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="Last Heartbeat",type=date,JSONPath=`.status.lastHeartbeatTime`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type ConnectedCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +kubebuilder:validation:Required
	Spec ConnectedClusterSpec `json:"spec"`

	// +optional
	Status ConnectedClusterStatus `json:"status,omitempty"`
}

// ConnectedClusterSpec is the desired state set by the portal at bundle-generation time.
type ConnectedClusterSpec struct {
	// bundleAPIs defines which provider-exported APIs are included in this bundle.
	//
	// +kubebuilder:validation:Required
	BundleAPIs BundleAPIs `json:"bundleAPIs"`
}

// BundleAPIs defines which provider-exported APIs are covered by a ConnectedCluster bundle.
// Exactly one of all or apis must express the selection:
//   - all: true    — the bundle covers every API exported by this provider.
//   - apis non-empty — the bundle covers exactly the listed APIs.
type BundleAPIs struct {
	// all, when true, means this bundle covers all APIs exported by this
	// provider. Mutually exclusive with apis. Immutable once set.
	//
	// +optional
	// +kubebuilder:validation:XValidation:rule="oldSelf == self",message="all is immutable once set"
	All bool `json:"all,omitempty"`

	// apis is the explicit set of exported APIs included in this bundle,
	// identified by CRD name ("<plural>.<group>"). Must contain at least one
	// entry when all is false. Must be empty when all is true.
	//
	// +optional
	// +listType=atomic
	APIs []APIRef `json:"apis,omitempty"`
}

// APIRef identifies an exported API by its CRD name on the provider,
// i.e. "<plural>.<group>" (for example "cowboys.wildwest.platform-mesh.io").
type APIRef struct {
	// name is the CRD name of the exported API, "<plural>.<group>".
	//
	// +required
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`
}

// ConnectedClusterStatus is the observed state updated by the ConnectedClusterReconciler.
type ConnectedClusterStatus struct {
	// localClusterUID is the consumer cluster's kube-system namespace UID —
	// identical to Connection.status.localClusterUID on the consumer side.
	// Set by the konnector when it first establishes its heartbeat Lease on the
	// provider (the value equals Lease.spec.holderIdentity). Immutable once set.
	// The ConnectedClusterReconciler uses this to match Leases to ConnectedClusters:
	// a Lease whose spec.holderIdentity equals this UID belongs to this bundle's
	// consumer.
	//
	// +optional
	// +kubebuilder:validation:XValidation:rule="oldSelf == '' || self == oldSelf",message="localClusterUID is immutable once set"
	LocalClusterUID string `json:"localClusterUID,omitempty"`

	// leaseRef points at the coordination.k8s.io/Lease maintained by the
	// konnector on this provider cluster as a heartbeat. Nil until the consumer
	// first connects. The Lease lives in the "kbind" namespace and is named
	// "consumer-<localClusterUID>".
	//
	// +optional
	LeaseRef *LocalLeaseRef `json:"leaseRef,omitempty"`

	// lastHeartbeatTime is the most recent time the konnector renewed its
	// heartbeat Lease on the provider cluster. Updated by the reconciler each
	// time it observes a fresh Lease.renewTime. Nil until the consumer first
	// connects.
	//
	// +optional
	LastHeartbeatTime *metav1.Time `json:"lastHeartbeatTime,omitempty"`

	// conditions:
	//   Connected — a Lease with matching holderIdentity exists and renewTime
	//               is within 2× leaseDurationSeconds (currently 120 s).
	//   Ready     — Connected is true and no internal errors.
	//
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// LocalLeaseRef is a namespace+name pointer to a coordination.k8s.io/Lease
// on this (provider) cluster.
type LocalLeaseRef struct {
	// namespace of the Lease.
	//
	// +required
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Namespace string `json:"namespace"`

	// name of the Lease.
	//
	// +required
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`
}

// ConnectedClusterList contains a list of ConnectedCluster.
//
// +kubebuilder:object:root=true
type ConnectedClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectedCluster `json:"items"`
}
