//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIRef) DeepCopyInto(out *APIRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIRef.
func (in *APIRef) DeepCopy() *APIRef {
	if in == nil {
		return nil
	}
	out := new(APIRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleAPIs) DeepCopyInto(out *BundleAPIs) {
	*out = *in
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]APIRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleAPIs.
func (in *BundleAPIs) DeepCopy() *BundleAPIs {
	if in == nil {
		return nil
	}
	out := new(BundleAPIs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectedCluster) DeepCopyInto(out *ConnectedCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectedCluster.
func (in *ConnectedCluster) DeepCopy() *ConnectedCluster {
	if in == nil {
		return nil
	}
	out := new(ConnectedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectedCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectedClusterList) DeepCopyInto(out *ConnectedClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectedClusterList.
func (in *ConnectedClusterList) DeepCopy() *ConnectedClusterList {
	if in == nil {
		return nil
	}
	out := new(ConnectedClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectedClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectedClusterSpec) DeepCopyInto(out *ConnectedClusterSpec) {
	*out = *in
	in.BundleAPIs.DeepCopyInto(&out.BundleAPIs)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectedClusterSpec.
func (in *ConnectedClusterSpec) DeepCopy() *ConnectedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectedClusterStatus) DeepCopyInto(out *ConnectedClusterStatus) {
	*out = *in
	if in.LeaseRef != nil {
		in, out := &in.LeaseRef, &out.LeaseRef
		*out = new(LocalLeaseRef)
		**out = **in
	}
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectedClusterStatus.
func (in *ConnectedClusterStatus) DeepCopy() *ConnectedClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectedClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalLeaseRef) DeepCopyInto(out *LocalLeaseRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalLeaseRef.
func (in *LocalLeaseRef) DeepCopy() *LocalLeaseRef {
	if in == nil {
		return nil
	}
	out := new(LocalLeaseRef)
	in.DeepCopyInto(out)
	return out
}
