apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
    ui.platform-mesh.io/content-for: kbind-provider.platform-mesh.io
  name: kbind-provider.platform-mesh.io
spec:
  inlineConfiguration:
    content: |-
      {
          "name": "kbind-ui",
          "luigiConfigFragment": {
              "data": {
                  "nodes": [
                      {
                          "pathSegment": "kbind",
                          "label": "kbind",
                          "hideFromNav": false,
                          "icon": "chain-link",
                          "url": "https://{context.organization}.portal.localhost:8443/kbind/",
                          "entityType": "main.core_platform-mesh_io_account",
                          "order": 800,
                          "context": {
                              "accountId": ":core_platform-mesh_io_accountId"
                          }
                      }
                  ],
                  "texts": [
                      {
                          "locale": "",
                          "textDictionary": {
                              "kbind": "kbind"
                          }
                      },
                      {
                          "locale": "en",
                          "textDictionary": {
                              "kbind": "kbind"
                          }
                      }
                  ]
              }
          }
      }
    contentType: json
